import { readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const rootDir = process.cwd();
const tempDir = path.join(rootDir, '.gas-build');
const outputFile = path.join(rootDir, 'gas', 'Code.js');

const orderedFiles = [
  'types.js',
  'config.js',
  'utils.js',
  'repository.js',
  'services.js',
  'controller.js',
  'entrypoints.js'
];

async function readChunk(fileName) {
  const fullPath = path.join(tempDir, fileName);
  try {
    const content = await readFile(fullPath, 'utf8');
    return `// ----- ${fileName} -----\n${content.trimEnd()}`;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Missing compiled GAS chunk: ${fileName}. ${message}`);
  }
}

async function buildGasBundle() {
  const chunks = await Promise.all(orderedFiles.map((fileName) => readChunk(fileName)));
  const header = [
    '/**',
    ' * Generated from gas/src/*.ts by scripts/build-gas.mjs.',
    ' * Do not edit this file directly.',
    ' */',
    ''
  ].join('\n');
  const output = `${header}${chunks.join('\n\n')}\n`;
  await writeFile(outputFile, output, 'utf8');
  await rm(tempDir, { recursive: true, force: true });
}

await buildGasBundle();
